<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Adamantium.Vulkan\Adamantium.Vulkan.csproj" />
    <ProjectReference Include="..\Adamantium.Vulkan.SpirvTools\Adamantium.Vulkan.SpirvTools.csproj" />
    <ProjectReference Include="..\Adamantium.Vulkan.Spirv\Adamantium.Vulkan.Spirv.csproj" />
    <ProjectReference Include="..\Adamantium.Vulkan.Slang\Adamantium.Vulkan.Slang.csproj" />
    <ProjectReference Include="..\Adamantium.Vulkan.Loader\Adamantium.Vulkan.Loader.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Adamantium.Core">
      <HintPath>Adamantium.Core.dll</HintPath>
    </Reference>
    <Reference Include="Adamantium.Imaging">
      <HintPath>Adamantium.Imaging.dll</HintPath>
    </Reference>
    <Reference Include="Adamantium.Mathematics">
      <HintPath>Adamantium.Mathematics.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Textures\BaseAlbedoTexture_Text.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="shaders\BasicShader.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
