using QuantumBinding.Generator;
using QuantumBinding.Generator.CodeGeneration;
using QuantumBinding.Generator.ProcessingFluentApi;
using QuantumBinding.Generator.Processors;
using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.InteropServices;
using Adamantium.Vulkan.Generator.Extensions;
using Adamantium.Vulkan.Generator.Processors;
using QuantumBinding.Generator.Utils;

namespace Adamantium.Vulkan.Generator
{
    public class VulkanBindingGenerator : QuantumBindingGenerator
    {
        private Module vkMainModule;
        private Module spivCrossModule;
        private Module spivToolsModule;
        private Module slangModule;

        public override void OnSetup(BindingOptions options)
        {
            string header = @$"
            ----------------------------------------------------------------------------------------------
            <auto-generated>
            This file was autogenerated by {GeneratorName}.
            Do not edit this file manually because you will lose all your changes after the next generation.
            </auto-generated>
            ----------------------------------------------------------------------------------------------";
            
            string vkMainLibrary = "vulkan-1";
            string shadercLibrary = "shaderc_shared";
            string spirvCrossLibrary = "spirv-cross-c-shared";
            string spirvToolsLibrary = "SPIRV-Tools-shared";
            string slangLibrary = "slang-c-shared";
            string mainNamespace = "Adamantium.Vulkan";
            string vulkanBasePath = @"C:\VulkanSDK\1.4.350.0\Include";
            string vulkanXmlPath = "vk.xml";
            string interopSubNamespace = "Interop";

            var appRoot = AppContext.BaseDirectory.Substring(0, AppContext.BaseDirectory.LastIndexOf("bin"));
            string corePath = Path.GetFullPath(Path.Combine(appRoot, "..", "Adamantium.Vulkan", "Core" ,"Generated"));
            string windowsPath = Path.GetFullPath(Path.Combine(appRoot, "..", "Adamantium.Vulkan", "Windows", "Generated"));
            string macOSPath = Path.GetFullPath(Path.Combine(appRoot, "..", "Adamantium.Vulkan", "MacOS", "Generated"));
            string spirvPath = Path.GetFullPath(Path.Combine(appRoot, "..", "Adamantium.Vulkan.Spirv", "Generated"));
            var spirvToolsPath = (Path.Combine(appRoot, "..", "Adamantium.Vulkan.SpirvTools", "Generated"));
            var slangPath = Path.GetFullPath(Path.Combine(appRoot, "..", "Adamantium.Vulkan.Slang", "Generated"));
            var slangHeader = Path.GetFullPath(Path.Combine(appRoot, "..", "Adamantium.Vulkan.Slang", "native", "slang_c.h"));
            
            options.GenerateSequentialLayout = true;
            options.PodTypesAsSimpleTypes = false;
            options.PathToBindingsFile = "VulkanBindingsMap.xml";
            options.DebugMode = true;

            var namespaceMappings = new List<NamespaceMapping>();
            namespaceMappings.Add(new NamespaceMapping(){FileName = "vulkan_core", SubNamespace = "Core", OutputPath = corePath});
            namespaceMappings.Add(new NamespaceMapping(){FileName = "vulkan_win32", SubNamespace = "Windows", OutputPath = spirvPath});
            namespaceMappings.Add(new NamespaceMapping(){FileName = "vulkan_macos", SubNamespace = "MacOS", OutputPath = spirvToolsPath});
            var parserSettings = new VulkanParserSettings(namespaceMappings,["win32", "macos"]);
            parserSettings.IncludeVideoExtensions = true;
            parserSettings.VideoExtensionsPath = "video.xml";
            vkMainModule = Module.Create(vkMainLibrary, false).WithVulkanXmlParser(parserSettings);
            vkMainModule.GeneratorMode = GeneratorMode.Preview;
            vkMainModule.CleanPreviousGeneration = true;
            vkMainModule.EachTypeInSeparateFile = true;
            vkMainModule.FileHeader = header;
            vkMainModule.Name = "Core";
            vkMainModule.Defines.Add("_WIN32");
            vkMainModule.Defines.Add("_MSC_VER");
            vkMainModule.Defines.Add("VK_USE_PLATFORM_WIN32_KHR");
            vkMainModule.Defines.Add("VK_USE_PLATFORM_MACOS_MVK");
            vkMainModule.Files.AddRange(vulkanXmlPath);
            vkMainModule.ForceCallingConvention = false;
            vkMainModule.InteropClassAccessSpecifier = AccessSpecifier.Internal;
            vkMainModule.CallingConvention = CallingConvention.Winapi;
            vkMainModule.AllowConvertStructToClass = true;
            vkMainModule.MethodClassName = "VulkanNative";
            vkMainModule.InteropClassName = "VulkanInterop";
            vkMainModule.OutputFileName = mainNamespace;
            vkMainModule.OutputNamespace = mainNamespace;
            vkMainModule.InteropSubNamespace = interopSubNamespace;
            vkMainModule.AddNamespaceMapping("vulkan_core", "Core", corePath);
            vkMainModule.AddNamespaceMapping("vulkan_win32", "Windows", windowsPath);
            vkMainModule.AddNamespaceMapping("vulkan_macos", "MacOS", macOSPath);
            vkMainModule.WrapInteropObjects = true;
            vkMainModule.GenerateOverloadsForArrayParams = true;
            vkMainModule.GeneratorSpecializations = GeneratorSpecializations.All;
            vkMainModule.OutputPath = corePath;
            vkMainModule.TargetRuntime = TargetRuntime.Net8Plus;
            
            var spirvCrossSpecs = GeneratorSpecializationUtils.AllExcept(GeneratorSpecializations.Macros);
            spivCrossModule = Module.Create(spirvCrossLibrary);
            spivCrossModule.FileHeader = header;
            spivCrossModule.GeneratorMode = GeneratorMode.Compatible;
            spivCrossModule.EachTypeInSeparateFile = true;
            spivCrossModule.CleanPreviousGeneration = true;
            spivCrossModule.Name = "Spirv.Cross";
            spivCrossModule.Files.Add(Path.Combine(vulkanBasePath, "spirv_cross", "spirv_cross_c.h"));
            spivCrossModule.Defines.Add("SPVC_EXPORT_SYMBOLS");
            spivCrossModule.Defines.Add("_MSC_VER");
            spivCrossModule.ForceCallingConvention = true;
            spivCrossModule.CallingConvention = CallingConvention.Winapi;
            spivCrossModule.AllowConvertStructToClass = true;
            spivCrossModule.MethodClassName = "SpirvCrossNative";
            spivCrossModule.InteropClassName = "SpirvCrossInterop";
            spivCrossModule.GeneratorSpecializations = spirvCrossSpecs;
            spivCrossModule.OutputFileName = "Adamantium.Vulkan.Spirv.Cross";
            spivCrossModule.OutputNamespace = "Adamantium.Vulkan.Spirv.Cross";
            spivCrossModule.InteropSubNamespace = interopSubNamespace;
            spivCrossModule.AddNamespaceMapping("spirv", "Adamantium.Vulkan.Spirv", spirvPath, true);
            spivCrossModule.WrapInteropObjects = true;
            spivCrossModule.CharAsBoolForMethods = true;
            spivCrossModule.OutputPath = spirvPath;
            spivCrossModule.TargetRuntime = TargetRuntime.NetStandard20;
            
            var spirvToolsSpecs = GeneratorSpecializationUtils.AllExcept(GeneratorSpecializations.Macros);
            spivToolsModule = Module.Create(spirvToolsLibrary);
            spivToolsModule.FileHeader = header;
            spivToolsModule.GeneratorMode = GeneratorMode.Compatible;
            spivToolsModule.EachTypeInSeparateFile = true;
            spivToolsModule.CleanPreviousGeneration = true;
            spivToolsModule.Name = "SpirvTools";
            spivToolsModule.Files.Add(Path.Combine(vulkanBasePath, "spirv-tools", "libspirv.h"));
            spivToolsModule.Defines.Add("SPIRV_TOOLS_EXPORT");
            spivToolsModule.Defines.Add("_WIN32");
            spivToolsModule.ForceCallingConvention = true;
            spivToolsModule.CallingConvention = CallingConvention.Winapi;
            spivToolsModule.AllowConvertStructToClass = true;
            spivToolsModule.MethodClassName = "SpirvToolsNative";
            spivToolsModule.InteropClassName = "SpirvToolsInterop";
            spivToolsModule.GeneratorSpecializations = spirvToolsSpecs;
            spivToolsModule.OutputFileName = "Adamantium.Vulkan.SpirvTools";
            spivToolsModule.OutputNamespace = "Adamantium.Vulkan.SpirvTools";
            spivToolsModule.InteropSubNamespace = interopSubNamespace;
            spivToolsModule.AddNamespaceMapping("libspirv", "Adamantium.Vulkan.SpirvTools", spirvToolsPath, true);
            spivToolsModule.WrapInteropObjects = true;
            spivToolsModule.CharAsBoolForMethods = true;
            spivToolsModule.OutputPath = spirvToolsPath;
            spivToolsModule.TargetRuntime = TargetRuntime.NetStandard20;

            // Our own thin C facade over the Slang compiler (native: slang-c-shared.dll).
            var slangSpecs = GeneratorSpecializationUtils.AllExcept(GeneratorSpecializations.Macros);
            slangModule = Module.Create(slangLibrary);
            slangModule.FileHeader = header;
            slangModule.GeneratorMode = GeneratorMode.Compatible;
            slangModule.EachTypeInSeparateFile = true;
            slangModule.CleanPreviousGeneration = true;
            slangModule.Name = "Slang";
            slangModule.Files.Add(slangHeader);
            slangModule.Defines.Add("_WIN32");   // makes SLANGC_API = __declspec(dllexport) so the funcs are seen as exported
            slangModule.Defines.Add("_MSC_VER");
            slangModule.ForceCallingConvention = true;
            slangModule.CallingConvention = CallingConvention.Winapi;
            slangModule.AllowConvertStructToClass = true;
            slangModule.MethodClassName = "SlangNative";
            slangModule.InteropClassName = "SlangInterop";
            slangModule.GeneratorSpecializations = slangSpecs;
            slangModule.OutputFileName = "Adamantium.Vulkan.Slang";
            slangModule.OutputNamespace = "Adamantium.Vulkan.Slang";
            slangModule.InteropSubNamespace = interopSubNamespace;
            slangModule.WrapInteropObjects = true;
            slangModule.OutputPath = slangPath;
            slangModule.TargetRuntime = TargetRuntime.NetStandard20;

            options.AddModule(vkMainModule);
            options.AddModule(spivCrossModule);
            options.AddModule(spivToolsModule);
            options.AddModule(slangModule);
        }

        public override void OnBeforeSetupPasses(ProcessingContext context)
        {
            VulkanBindings.ProvideFunctionsForParametersFix(context);
            VulkanBindings.ReplaceTypedefsToEnums(context);
        }

        public override void OnSetupPostProcessing(ProcessingContext context)
        {
            var functionToInstance = new FunctionToInstanceMethodPass();
            functionToInstance.SkipOverloadForFunctions(
                "vkEnumeratePhysicalDevices", 
                "vkGetPhysicalDeviceSurfaceFormatsKHR",
                "vkGetPhysicalDeviceSurfacePresentModesKHR",
                "vkGetPhysicalDeviceQueueFamilyProperties",
                "vkEnumerateDeviceExtensionProperties",
                "vkEnumerateInstanceExtensionProperties",
                "vkEnumerateInstanceLayerProperties",
                "vkCmdPipelineBarrier");
            
            context.AddPreGeneratorPass(functionToInstance, ExecutionPassKind.PerTranslationUnit);
            context.AddPreGeneratorPass(new DispatchTableProcessorPass(), ExecutionPassKind.PerTranslationUnit);
            context.AddPreGeneratorPass(new ForceCallingConventionPass(CallingConvention.Winapi), ExecutionPassKind.PerTranslationUnit);
            context.AddPreGeneratorPass(new CheckFlagsEnumsPass(), ExecutionPassKind.PerTranslationUnit);
            context.AddPreGeneratorPass(new EnumItemsCleanupPass(), ExecutionPassKind.PerTranslationUnit);
            context.AddPreGeneratorPass(new EnumItemsRenamePass(CasePattern.PascalCase, "VkFormat"), ExecutionPassKind.PerTranslationUnit);
            context.AddPreGeneratorPass(new EnumItemsExcludePass(ExcludeCheck.StartsWithIgnoreCase, "BeginRange", "EndRange"), ExecutionPassKind.PerTranslationUnit);
            
            var renameTargets = RenameTargetsUtils.AnyExcept(RenameTargets.Struct | RenameTargets.Union | RenameTargets.Function);
            var vkRenameItems = new List<RegexRenameRunItem>()
            {
                new RegexRenameRunItem("^vkCmd", string.Empty, renameTargets, true),
                new RegexRenameRunItem("^vk", string.Empty, renameTargets, true),
            };
            context.AddPreGeneratorPass(new SequentialRegexRenamePass(vkRenameItems.ToArray()), ExecutionPassKind.PerTranslationUnit, vkMainModule);

            renameTargets = RenameTargetsUtils.AnyExcept(RenameTargets.Function | RenameTargets.Struct);

            var spirvRenameTargets = RenameTargetsUtils.AnyExcept(RenameTargets.Function).
                Except(RenameTargets.Struct).
                Except(RenameTargets.Union);

            var spvcRenameItems = new List<RegexRenameRunItem>()
            {
                new RegexRenameRunItem("^spvc_resources", string.Empty, RenameTargets.Method, true),
                new RegexRenameRunItem("^spvc_compiler_options", string.Empty, RenameTargets.Method, true),
                new RegexRenameRunItem("^spvc_compiler", string.Empty, RenameTargets.Method, true),
                new RegexRenameRunItem("^spvc_constant", string.Empty, RenameTargets.Method, true),
                new RegexRenameRunItem("^spvc_context", string.Empty, RenameTargets.Method, true),
                new RegexRenameRunItem("^spvc_type", string.Empty, RenameTargets.Method, true),
                new RegexRenameRunItem("^spvc", "spirv", RenameTargets.Class, true),
                new RegexRenameRunItem("^spvc", string.Empty, spirvRenameTargets, false),
                new RegexRenameRunItem("^spv", string.Empty, spirvRenameTargets, true),
            };

            context.AddPreGeneratorPass(new SequentialRegexRenamePass(spvcRenameItems.ToArray()), ExecutionPassKind.PerTranslationUnit, spivCrossModule);
            context.AddPreGeneratorPass(new CaseRenamePass(renameTargets, CasePattern.PascalCase), ExecutionPassKind.PerTranslationUnit, spivCrossModule);

            var slangRenameItems = new List<RegexRenameRunItem>()
            {
                new RegexRenameRunItem("^slangc_", string.Empty, RenameTargets.Method, true),
            };
            context.AddPreGeneratorPass(new SequentialRegexRenamePass(slangRenameItems.ToArray()), ExecutionPassKind.PerTranslationUnit, slangModule);
            context.AddPreGeneratorPass(new CaseRenamePass(renameTargets, CasePattern.PascalCase), ExecutionPassKind.PerTranslationUnit, slangModule);

            var disposableList = new List<DisposableExtension>();
            disposableList.Add(new DisposableExtension() { Name = "Instance", DisposableContent = "DestroyInstance();" });
            disposableList.Add(new DisposableExtension() { Name = "Device", DisposableContent = "DestroyDevice();" });

            var disposable = new DisposableExtensionPass(disposableList.ToArray()) { OutputFileName = "Extensions", GeneratorSpecializations = GeneratorSpecializations.Extensions};
            context.AddCodeGenerationPass(disposable, ExecutionPassKind.PerTranslationUnit);

            var macroAction = new MacroFunctionsToCSharpFunctionsPass();
            macroAction.IgnoreList.Add("VK_USE_PLATFORM_WIN32_KHR");
            macroAction.IgnoreList.Add("_WIN32");
            macroAction.IgnoreList.Add("VULKAN_H_");
            macroAction.IgnoreList.Add("VKAPI_CALL");
            macroAction.IgnoreList.Add("VULKAN_CORE_H_");
            macroAction.IgnoreList.Add("VKAPI_PTR");
            macroAction.IgnoreList.Add("VK_NULL_HANDLE");
            macroAction.IgnoreList.Add("VK_DEFINE_HANDLE");
            macroAction.IgnoreList.Add("VK_DEFINE_NON_DISPATCHABLE_HANDLE");
            macroAction.IgnoreList.Add("SHADERC_EXPORT");
            macroAction.IgnoreList.Add("SHADERC_IMPLEMENTATION");
            macroAction.IgnoreList.Add("SHADERC_SHAREDLIB");
            macroAction.IgnoreList.Add("VK_MAKE_VERSION");
            macroAction.IgnoreList.Add("VK_VERSION_MAJOR");
            macroAction.IgnoreList.Add("VK_VERSION_MINOR");
            macroAction.IgnoreList.Add("VK_VERSION_PATCH");
            macroAction.IgnoreList.Add("VKSC_API_VERSION_1_0");
            macroAction.IgnoreList.Add("VK_HEADER_VERSION_COMPLETE");
            
            macroAction.SubstitutionList.Add("VK_MAKE_API_VERSION", VulkanBindings.MacroFunctions.CreateMakeApiVersionFunction());
            macroAction.SubstitutionList.Add("VK_API_VERSION_VARIANT", VulkanBindings.MacroFunctions.CreateApiVersionFor("variant"));
            macroAction.SubstitutionList.Add("VK_API_VERSION_MAJOR", VulkanBindings.MacroFunctions.CreateApiVersionFor("major"));
            macroAction.SubstitutionList.Add("VK_API_VERSION_MINOR", VulkanBindings.MacroFunctions.CreateApiVersionFor("minor"));
            macroAction.SubstitutionList.Add("VK_API_VERSION_PATCH", VulkanBindings.MacroFunctions.CreateApiVersionFor("patch"));
            macroAction.SubstitutionList.Add("VK_API_VERSION_1_0", VulkanBindings.MacroFunctions.CreateApiVersion());
            macroAction.SubstitutionList.Add("VK_API_VERSION_1_1", VulkanBindings.MacroFunctions.CreateApiVersion());
            macroAction.SubstitutionList.Add("VK_QUEUE_FAMILY_EXTERNAL_KHR", VulkanBindings.MacroFunctions.CreateApiVersion());
            macroAction.SubstitutionList.Add("VK_QUEUE_FAMILY_EXTERNAL", VulkanBindings.MacroFunctions.CreateApiVersion());
            macroAction.SubstitutionList.Add("VK_QUEUE_FAMILY_FOREIGN_EXT", VulkanBindings.MacroFunctions.CreateApiVersion());
            macroAction.SubstitutionList.Add("VK_HEADER_VERSION", VulkanBindings.MacroFunctions.CreateHeaderVersion());
            macroAction.SubstitutionList.Add("VK_LOD_CLAMP_NONE", VulkanBindings.MacroFunctions.CreateLodClampNone());
            macroAction.SubstitutionList.Add("VK_KHR_MAINTENANCE1_EXTENSION_NAME", VulkanBindings.MacroFunctions.CreateStringReturnMacro());
            macroAction.SubstitutionList.Add("VK_KHR_MAINTENANCE2_EXTENSION_NAME", VulkanBindings.MacroFunctions.CreateStringReturnMacro());
            macroAction.SubstitutionList.Add("VK_KHR_MAINTENANCE3_EXTENSION_NAME", VulkanBindings.MacroFunctions.CreateStringReturnMacro());
            macroAction.SubstitutionList.Add("VK_NV_VIEWPORT_ARRAY2_EXTENSION_NAME", VulkanBindings.MacroFunctions.CreateStringReturnMacro());
            macroAction.SubstitutionList.Add("VK_GOOGLE_HLSL_FUNCTIONALITY1_EXTENSION_NAME", VulkanBindings.MacroFunctions.CreateStringReturnMacro());
            
            macroAction.SubstitutionList.Add("VP_KHR_ROADMAP_2022_MIN_API_VERSION", VulkanBindings.MacroFunctions.CreateMakeProfileVersionFunction(1, 3, 204));
            macroAction.SubstitutionList.Add("VP_LUNARG_DESKTOP_BASELINE_2022_MIN_API_VERSION", VulkanBindings.MacroFunctions.CreateMakeProfileVersionFunction(1, 1, 139));
            
            // Spirv constansts part
            macroAction.IgnoreList.Add("SPVC_PUBLIC_API");
            macroAction.IgnoreList.Add("SPVC_TRUE");
            macroAction.IgnoreList.Add("SPVC_FALSE");
            
            macroAction.SubstitutionList.Add("SPVC_MAKE_MSL_VERSION", VulkanBindings.MacroFunctions.CreateSpirvMSLVersion());
            macroAction.SubstitutionList.Add("VK_MAKE_VIDEO_STD_VERSION", VulkanBindings.MacroFunctions.CreateMakeVideoStdVersion());
            
            context.AddPreGeneratorPass(macroAction, ExecutionPassKind.PerTranslationUnit);
        }

        public override void OnSetupComplete(ProcessingContext context)
        {
            var renameTargets =
                RenameTargetsUtils.AnyExcept(RenameTargets.Struct | RenameTargets.Union | RenameTargets.Function);
            var vkRenameItems = new List<RegexRenameRunItem>()
            {
                new RegexRenameRunItem("^vkCmd", string.Empty, renameTargets, true),
                new RegexRenameRunItem("^vk", string.Empty, renameTargets, true),
            };
            context.AddPreGeneratorPass(new SequentialRegexRenamePass(vkRenameItems.ToArray()), ExecutionPassKind.PerTranslationUnit, vkMainModule);
            context.AddCodeGenerationPass(new VulkanCodeGeneratorPass(), ExecutionPassKind.PerTranslationUnit);
        }
    }

}
