<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <Configurations>Debug;Release</Configurations>
        <LangVersion>latestmajor</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="QuantumBinding.Utils" Version="3.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="SPIRV-Tools-shared.dll" />
      <Content Include="SPIRV-Tools-shared.dll">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
